global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'Rock Paper Scissors Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Rock Paper Scissors Spring Boot Application'
